waitFor method support
WhatDaFox/Codeception-Mailtrap pull request #27
Opened 2018-04-26 14:24 UTC by polevaultweb

Resolves https://github.com/WhatDaFox/Codeception-Mailtrap/issues/26

2018-04-26 16:27 UTC, polevaultweb commented
@foxted I might need to change this, as its tightly coupled to phpunit 5.x

2018-04-26 20:23 UTC, foxted commented
Yes, ideally, I'd like to keep the current dependencies. But I really like this feature idea @polevaultweb, thanks for the initiative :)

2018-04-27 06:42 UTC, polevaultweb commented
@foxted I obviously didn't have enough coffee. Fixed up!

2018-05-01 21:27 UTC, foxted requested changes

2018-05-01 21:27 UTC, foxted commented on src/MailtrapWait.php
> +	public function until($func_or_ec, $message = '')
@polevaultweb I think we could make this a little clearer when it comes to naming variables. Wanna give it a shot?

2018-05-01 21:27 UTC, foxted commented on src/MailtrapWait.php
> +	public function __construct(Mailtrap $mailtrap, $timeout_in_second = null, $interval_in_millisecond = null)
Small detail, but it's missing a docblock :)

2018-05-02 14:41 UTC, polevaultweb commented
@foxted how's this?

2018-05-03 06:37 UTC, foxted approved these changes

2018-05-03 06:37 UTC, merged